### ISSUE TITLE
Добавить скрол на страницу Заявления на отпуск/отгул

### ISSUE THREAD

**Issue by estetsenko** [itru/timesheet#20]
При большом периоде дат не все записи помещаются. Было бы здорово, если добавить скрол на страницу просмотра графика отпусков.
![scroll](https://cloud.githubusercontent.com/assets/668162/5557823/53cfd038-8d1f-11e4-909b-e0e2659599d4.png)

**Comment by se-aplana** [comment]
есть в 1.6.1
