### ISSUE TITLE
не читается файл отчетов

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#21]
В формировании отчетов в отчете №2 не читаются буквы при выгрузке на одном из пк.
На другом пк все ок.
В чем может быть проблема? Шрифты?
Почему недоступна выгрузка в форматах html и pdf?

**Comment by se-aplana** [comment]
Проблема только в отчете №2 или во всех отчетах?
Какие локаль в ОС и браузере установлены на этих машинах?

Выгрузка в html и pdf отключены в коде т.к. не используются в работе, соотвественно не выполняется их доработка и тестирование.

**Comment by vdvas** [comment]
Проблема во всех отчетах.
Локаль в ОС это что?
Если имеется ввиду настройки "язык и региональные настройки" то руский.
В хроме тоже русский.
Шрифт установлен.

**Comment by se-aplana** [comment]
Можете прислать выгруженный файл с неверной кодировкой?

**Comment by vdvas** [comment]
http://rusfolder.com/43231684
пароль 123456

**Comment by se-aplana** [comment]
у вас проблемы только в названии файла или в самом документе тоже текст не читается?

**Comment by vdvas** [comment]
Только в самом документе где шрифт sansserif.

**Comment by se-aplana** [comment]
У меня файл открылся нормально. Видимо это локальные проблемы настройки.
Возможно office не имеет доступа к шрифту? В списке шрифтов он присудствует?

**Comment by vdvas** [comment]
В тот то и дело что проблема локальная.
ОС переустанавливали.
Каким образом офис не может иметь доступа к шрифту?
В списке шрифтов через панель управления (или в папке c:\windows\fonts) sansserif присутствует.

**Comment by se-aplana** [comment]
ОС переустанавливали - т.е. на свежеустановленной ОС таже проблема? Можете описать окружение (версии ОС, ПО, что еще установлено и т.п.)?

**Comment by vdvas** [comment]
Да, на свежеустановленной та же проблема.
windows 7 pro x64 sp1
office 2013 x32
google chrome
windows update установлены

**Comment by se-aplana** [comment]
К сожалению нам не удается воспроивезсти ситуацию.
Попробуйте обратиться в поддержку Microsoft, возможно они смогут сказать в чем проблема.

**Comment by vdvas** [comment]
Возможно поменять шрифт отчета? Со стороны таймшита.

**Comment by se-aplana** [comment]
Нет, это заложено в коде приложения.
Вы не пробовали менять шрифт уже в документе?
В шапке и в таблице используются разные шрифты, оба отображаются не корректно?
