### ISSUE TITLE
удаление  сотрудников из таблицы employee

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#22]
При попытке удалить сотрудника возникает ошибка, требуется удалить различные связи.
В таблице отвечающей за отчеты очень много значений, удалять их долго.
Возможно ли как то упростить процедуру удаления пользователей, проектов и должностей?

Ошибка SQL:

ОШИБКА:  UPDATE или DELETE в таблице "employee" нарушает ограничение внешнего ключа "fk_employee" таблицы "employee_permissions"
DETAIL:  На ключ (id)=(624) всё ещё есть ссылки в таблице "employee_permissions".
В операторе:
DELETE FROM "public"."employee" WHERE "id"='624'

**Comment by se-aplana** [comment]
В приложении не предусмотрено удаление сотрудников/проектов/должностей, т.к. у сотрудников есть списания по проектам в соответствующих должностях и они хранятся для отчетности.

Если нужно полностью очистить базу - то можно равернуть дамп из дистрибутива.

Если же необходимо очистить определенные записи - это возможно сделать только средствами СУБД.
Например, отключить проверку зависимостей и удалить записи, потом активировать зависимости или отследить все существующие зависимости и выполнить соотвествующий скрипт который будет удалять все последовательно.
PS: Перед выполнением подобных работ рекомендуется сделать полный дамп БД для отката.

**Comment by vdvas** [comment]
Отключать проверку зависимостей нужно в таблицах, в которые есть записи связанные с определенным сотрудником?
Или в таблице employee можно отключить зависимости?

**Comment by se-aplana** [comment]
отключение зависимостей позволит только удалть запись, но зависимые записи по прежнему будут в базе и непозволят включить зависимости обратно.

в любом случае нужно проверить все зависимости и последовательно удалить все записи мешающие удалить необходимую.
