### ISSUE TITLE
центр списания

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#24]
Центры списания занятости по проектам
Чтобы сотрудник мог сформировать отчет по проекту, необходимо, чтобы его подразделение было выбрано в качестве центра списания занятости. При этом остальные сотрудники, входящие в это же подразделение, тоже будут видеть данный проект в списке, хотя они могут быть там не задействованы.
Было бы удобнее, если это возможно сделать, чтобы у каждого сотрудника появлялись лишь те проекты, в которых они вписаны. Иначе люди будут путаться.

**Comment by KarinaIslamuratova** [comment]
Сейчас реализовано так, что сотрудники центра могут списывать занятость на проекты центра по умолчанию без ограничений. Чтобы сотрудники других центров могли списывать занятость на проекты этого центра, нужно настроить это на вкладке Администрирование - Редактирование проектов.
Возможность о которой Вы говорите будет не очень удобна для использования в крупных компаниях, где работает много сотрудников. Так как возможны ситуации, что проектов много и некоторые сотрудники работают попеременно на нескольких проектах. Для того, чтобы фиксировать какой сотрудник работает на каком проекте будет затронуто много рабочего времени администраторов, которые занимаются занесением информации о проектах в систему.
Ваше предложение рассмотрим и возможно используем в будущем для доработки системы.

**Comment by vdvas** [comment]
Сотрудников не так много.
Возможность реализовать привязку конкретного сотрудника к проекту возможно на данный момент?

**Comment by KarinaIslamuratova** [comment]
На данный момент такой возможности в системе не предусмотрено
