### ISSUE TITLE
Репозиторий maven недоступен

### ISSUE THREAD

**Issue by number133** [itru/timesheet#26]
Недоступен репозиторий на http://192.168.102.17, что не позволяет собрать проект

**Comment by se-aplana** [comment]
сборка должна проходить и без него. попробуйте удалить ссылку и пересобрать. если ошибка останется то вышлите лог.

**Comment by number133** [comment]
Не находятся зависимости:
<dependency>
                        <groupId>org.apache.maven.surefire</groupId>
                        <artifactId>surefire-junit4</artifactId>
                        <version>${surefire-junit4.version}</version>
                    </dependency>
<dependency>
            <groupId>lib.padeg</groupId>
            <artifactId>padeg</artifactId>
            <version>3.3.0.24</version>
            <scope>provided</scope>
        </dependency>

Лог:
D:\Projects2\timesheet>mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building TimeSheet 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/lib/padeg/padeg/3.3.0.24/padeg-3.3.0.24.pom
[WARNING] The POM for lib.padeg:padeg:jar:3.3.0.24 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/lib/padeg/padeg/3.3.0.24/padeg-3.3.0.24.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.130 s
[INFO] Finished at: 2015-04-07T10:07:44+06:00
[INFO] Final Memory: 12M/160M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project TimeSheet: Could not resolve dependencies for project com.aplana.timesheet:TimeSheet:war:1.0-SNAPSHOT: Could not find artifact l
ib.padeg:padeg:jar:3.3.0.24 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by number133** [comment]
Нашел решение тут
https://github.com/itru/timesheet/issues/9
Добавьте, пожалуйста, в readme пункт добавления библиотеки padeg в репозиторий.
Спасибо
