### ISSUE TITLE
Вопросы по отчетам

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#29]
При сохранении отчета бывает, что система пишет, что отчет сохранен, а на самом деле не так.
Т.е. в просмотре отчетов этого отчета нет.

А бывает, что при сохранении отчета слетают заполненные данные.
При попытке сохранения отчета, системы начинает сама менять введенные данные,
Меняются активности, задачи.
В итоге отчет не согранить.

Также вопрос с комментариями в отчете – возможно ли сделать это поле необязательным?

Если вводить отчет и забыть где-то проставить комментарий, то при отправке или сохранении для доработки он ругается, что поле не заполнено, при этом сбиваются уже заполненные поля (активности, задачи), приходится вводить заново.

**Comment by SvetaKudryavtseva** [comment]
1) Баг не воспроизводится, не могли бы Вы подробнее описать шаги
2) Баг зафиксирован, будем исправлять
3) Предполагается, что поле "Комментарий" обязательное, так как "Активность" и "Задача" не описывают детально проделанную работу. После исправления выше упомянутого бага проблем в случае не заполнения не будет

**Comment by SvetaKudryavtseva** [comment]
2) Баг исправлен в новой версии
3) По полю комментарий - поле можно сделать необязательным, для этого необходимо доработать код, который находится в открытом доступе
