### ISSUE TITLE
Странная ситуация с employee

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#30]
При удаление пользователя из таблицы employee через некоторое время он появляется там снова.
Такое происходит уже дважды с несколькими пользователями.
Возможно дело в неправильной настройке файла  /etc/tomcat6/timesheet.properties
Там есть строка где указывается active directory OU в котором должны находится удаленные пользователи.
ldap.ou.disabledEmployee=Disabled Users
Не очень ясно как указывать путь к этому OU.
Могли быть дать пояснение к этому параметру и в целом по проблеме с появлением пользователей в таблице employee?

**Comment by se-aplana** [comment]
>> Не очень ясно как указывать путь к этому OU.
Здесь должно быть указано имя OU в котором находятся деактивированные пользователи

>> и в целом по проблеме с появлением пользователей в таблице employee?
синхронизация с LDAP добавляет всех пользователей из каталога которые состоят в одном из центров. центры задаются в таблице division

если нужно чтобы пользователь игнорировался, нужно
либо поместить его в OU "ldap.ou.disabledEmployee"
либо убрать связь с центром (в LDAP поле department)

**Comment by vdvas** [comment]
Не ясно как это будет работать без указания ldap пути к OU.
Т.е. хотите сказать я создаю в произвольном месте OU Disabled Users, помещаю туда заблокированных пользователей и просто указываю в ldap.ou.disabledEmployee название OU с заблокированными пользователями?

**Comment by se-aplana** [comment]
Поиск выполняется по: OU={ldap.ou.disabledEmployee}
По умолчанию: OU=Disabled Users

С фильтром: ({ldap.field.objectClass}={ldap.objectClass.disabledEmployee})
По умолчанию: (objectClass=person)

Предполагается что "OU=Disabled Users" находится в корне дерева (параметр ldap.base)

**Comment by vdvas** [comment]
Пользователи все равно присутствуют в базе после переноса в контейнер Disabled Users, который находится в корне.
После удаления данных из полей в свойствах пользователя таких как  email, отдел, должность, город, руководитель; и синхронизации с ldap пользователи продолжают оставаться в базе.

**Comment by se-aplana** [comment]
система не удаляет пользователей из базы. им проставляются даты завершения работы и/или флаг неактивности. после чего нельзя списать занятость и войти в систему.

**Comment by vdvas** [comment]
В администрировании проектов отображаются все пользователи, в том числе  из контейнера Disabled Users.
Возможно ли их оттуда убрать или нет?

**Comment by se-aplana** [comment]
Нет. В текущей реализации это не предусмотрено и пока не планируется убирать.
