### ISSUE TITLE
Почтовая система

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#31]
Возможно ли указать даты за которые система просит сделать отчет?
Мы начали работать с системой в конце мая, а она просит отчеты с начала мая
Может ли она работать в ручном режиме, и не делать рассылку каждый день?
Возможно ли изменить ссылку в уведомлении "создать отчет"
Там стоит http://localhost:8080/timesheet?date=2015-05-05&id=60
Нужно поменять на имя сервера.
Возможно ли получить описание по работе этой почтовой системы?

**Comment by se-aplana** [comment]
> Возможно ли указать даты за которые система просит сделать отчет?
> Мы начали работать с системой в конце мая, а она просит отчеты с начала мая

укажите дату начала работы сотрудников с момента запуска системы (нужно руками обновить дату в таблице employee)

> Может ли она работать в ручном режиме, и не делать рассылку каждый день?

Можете изменить периодичность проверки, за это отвечает параметр:
scheduler.reportcheck - Рассылка сотрудникам напоминания о незаполненных отчетах

> Там стоит http://localhost:8080/timesheet?date=2015-05-05&id=60
> Нужно поменять на имя сервера.

За это отвечает параметр
timesheet.url - адрес сервера (подставляется в письма)

> Возможно ли получить описание по работе этой почтовой системы?

Что именно вас интересует?

**Comment by vdvas** [comment]
Возможно ли получить описание по работе этой почтовой системы?
Что именно вас интересует?
Как можно больше по принципам ее работы, и как можно на ее работу повлиять (т.е. администрирование).

**Comment by vdvas** [comment]
Понадобилось установить отправку почтовых оповещений на пятницу в 9 утра.
После изменения строки и перезагрузки сервера, ява перестала работать.
scheduler.reportcheck =           0 0  9 *  *  FRI *

**Comment by se-aplana** [comment]
Проверьте корректность введенных данных, наличие лишних символов и т.п.

Описание формата можно посмотреть здесь: http://www.quartz-scheduler.org/documentation/quartz-1.x/tutorials/crontrigger
