### ISSUE TITLE
Раздел обратная связь

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#32]
Возможно ли чтобы люди писали о проблемах в эту форму и эти сообщения можно было увидеть,?
А то у некоторых не работает, а они молчат.
Кому будут приходить письма из формы обратной связи?

**Comment by se-aplana** [comment]
##### Определение почтовых адресов ########################################################
#
# почтовый адрес отправителя во всех письмах рассылаемых системой
mail.fromaddress=
# почтовый адрес отправки писем для дебага
mail.debug.address=
# почтовый адреса для отправки писем с формы обратной связи
mail.ProblemsAndProposals.toaddress=
# почтовый адреса для отправки писем с формы обратной связи для "Создать\Удалить заявление на отпуск"
mail.ProblemsAndProposals.toAdminAddress=
