### ISSUE TITLE
Правка отчетов

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#33]
У некоторых пользователей были заполнены отчеты с ошибками в датах, нужно чтобы была возможность по просьбе править уже отправленные отчеты.
Кто это может делать, какие нужны для этого права?

**Comment by se-aplana** [comment]
Управление отчетами доступно пользователям системы с правами: 3 - Администрирование системы

Справочник прав в таблице permission
Права задаются в таблице employee_permissions

PS: Также возможно изменить дату отчета SQL: 
update time_sheet set caldate = '2015-04-08' where emp_id = ХХХ and caldate = '2015-04-09'
где, ХХХ - ID сотрудника

**Comment by vdvas** [comment]
У меня есть нужные права. Как я могу исправить мой отчет?
В разделе просмотр отчетов нет вижу как это сделать.

**Comment by se-aplana** [comment]
Можете показать скриншот страницы?

**Comment by vdvas** [comment]
![screen shot 06-22-15 at 09 39 am](https://cloud.githubusercontent.com/assets/9025124/8276734/9a4f30f6-18c2-11e5-877d-5dd04bc9bfce.PNG)

**Comment by se-aplana** [comment]
Нужна страница со списокм отчетов за месяц

**Comment by vdvas** [comment]
![default](https://cloud.githubusercontent.com/assets/9025124/8281134/aa05ca84-18ed-11e5-80c1-cc75ee1cf451.png)

**Comment by se-aplana** [comment]
отмечаете нужные отчеты галочкой и нажимаете в нижней части кнопку "удалить" или "в черновик"

после перевода в черновик, отчет можно изменить и отправить повторно.
