### ISSUE TITLE
Отчет №4. Сотрудники, не отправившие отчет

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#37]
В данном отчете не отображаются руководители центра.
Возможно ли это исправить?

**Comment by se-aplana** [comment]
такое поведение заложено в коде, штатного ключения их в отчеты не предусмотрено.

как обходное решение можно попробовать в таблице employee в столбце manager указать какоето значение (например самого себя или некую резервную запись)

это должно включить руководителей в отчет, но не исключено что проблемы возникнут в других местах (например при рассылке уведомлений список адресатов строится через это поле)
