### ISSUE TITLE
 Неопознанная ошибка при авторизации.

### ISSUE THREAD

**Issue by zzserg** [itru/timesheet#38]
Поставил систему по readme.md.
Дамп PgSQL закачался успешно (пришлось убрать --no-passwd и дважды указать пароль вручную).

При попытке авторизоваться в логах проскакивает
17:22:15.800 [qtp30864382-27] DEBUG o.s.s.w.a.UsernamePasswordAuthenticationFilt
er - Authentication request failed: org.springframework.security.authentication.
AccountExpiredException: Неопознанная ошибка при авторизации

Как убедиться, что account действительно expired?

И ещё есть ругань на отсутствующие поля в таблицах.
2015-07-23 19:01:13 MSK ОШИБКА:  колонка employee0_.birthday не существует (символ 68)
2015-07-23 19:01:13 MSK ОПЕРАТОР:  select employee0_.id as id30_, employee0_.billable as billable30_, employee0_.birthday as birthday30_, employee0_.division as division30_, employee0_.email as email30_, employee0_.end_date as end5_30_, employee0_.jira_name as jira6_30_, employee0_.job as job30_, employee0_.job_rate as job7_30_, employee0_.ldap as ldap30_, employee0_.manager as manager30_, employee0_.manager2 as manager17_30_, employee0_.name as name30_, employee0_.not_to_sync as not10_30_, employee0_.ldap_object_sid as ldap11_30_, employee0_.patronymic as patronymic30_, employee0_.region as region30_, employee0_.start_date as start13_30_ from employee employee0_ where employee0_.email=$1 limit $2

Можете обновить дампы DB и LDAP?

**Comment by zzserg** [comment]
Хочется запустить систему. Есть у кого рабочие дампы БД и LDAP?

**Comment by zzserg** [comment]
up

**Comment by zzserg** [comment]
up-up-up :)

**Comment by SvetaKudryavtseva** [comment]
Инструкция для обновления, дампы DB и LDAP будут обновлены в ближайшие дни. На основной странице на гитхабе появится информация об обновлении

**Comment by AlexAf** [comment]
Дамп базы данных обновлён. Дамп LDAP был актуальным. Попробуйте развернуть систему. Если возникнут проблемы - пишите сюда.

**Comment by w-e-g** [comment]
Добрый день!

Развернул систему на базе Centos 7, openldap 2.4.40. Есть проблема при подключении:

6:12:19.633 [qtp1738551919-24] DEBUG o.s.s.ldap.search.FilterBasedLdapUserSearch - Searching for user 'Boss', with user search [ searchFilter: '(uid={0})', searchBase: '', scope: subtree, searchTimeLimit: 0, derefLinkFlag: false ]
16:12:19.635 [qtp1738551919-24] DEBUG o.s.ldap.core.support.AbstractContextSource - Got Ldap context on server 'ldap://localhost:389/dc=example,dc=com'
16:12:19.637 [qtp1738551919-24] DEBUG o.s.security.ldap.SpringSecurityLdapTemplate - Searching for entry under DN 'dc=example,dc=com', base = '', filter = '(uid={0})'
16:12:19.637 [qtp1738551919-24] DEBUG o.s.security.ldap.SpringSecurityLdapTemplate - Found DN: cn=Boss,ou=Users
16:12:19.638 [qtp1738551919-24] DEBUG o.s.s.ldap.authentication.BindAuthenticator - Attempting to bind as cn=Boss,ou=Users,dc=example,dc=com
16:12:19.641 [qtp1738551919-24] DEBUG o.s.ldap.core.support.AbstractContextSource - Got Ldap context on server 'ldap://localhost:389/dc=example,dc=com'
16:12:19.641 [qtp1738551919-24] DEBUG o.s.s.ldap.authentication.BindAuthenticator - Retrieving attributes...
16:12:19.645 [qtp1738551919-24] ERROR c.a.timesheet.service.LdapUserDetailsService - Неопознанная ошибка при авторизации
org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute query; SQL [select employee0_.id as id21_, employee0_.billable as billable21_, employee0_.birthday as birthday21_, employee0_.division as division21_, employee0_.email as email21_, employee0_.end_date as end5_21_, employee0_.jira_name as jira6_21_, employee0_.job as job21_, employee0_.job_rate as job7_21_, employee0_.ldap as ldap21_, employee0_.manager as manager21_, employee0_.manager2 as manager17_21_, employee0_.name as name21_, employee0_.not_to_sync as not10_21_, employee0_.ldap_object_sid as ldap11_21_, employee0_.patronymic as patronymic21_, employee0_.region as region21_, employee0_.start_date as start13_21_ from employee employee0_ where employee0_.email=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute query

Судя по ошибке — отбрасывает сам openldap. Куда смотреть?

btw, у вас похоже какие-то очень старые конфиги ldap используются. Начиная с openldap 2.4.  отказались от slapd.conf и подгрузки через LDIF. Но пока прикрутил как есть.

**Comment by w-e-g** [comment]
Отбой, не заметил даты сначала и что вы свежие дампы залили. Дропнул базу и залил свежие — взлетело. Сенкс.

**Comment by zzserg** [comment]
Дроп базы + пересборка проекта.
Взлетело, спасибо!
