### ISSUE TITLE
Долго отправляет отчет

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#39]
С недавнего времени у всех пользователей стал долго отправляться отчет. Около минуты.
Как это можно исправить?

**Comment by se-aplana** [comment]
Проверьте производительность системы где выполняется процесс. У нас работает уже несколько лет, количество пользователей более 350, количество отчетов более 70 тыс. (в среднем 1-2 строки в кадом отчете). Никаких проблем производительности мы не наблюдаем.

**Comment by vdvas** [comment]
Имеете ввиду загрузку цпу, память, диски, сеть или загрузку tomcat, pgsql?

**Comment by se-aplana** [comment]
лучше посмотреть все что можно
