### ISSUE TITLE
Заявления на отпуск/отгул

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#40]
После формирования заявления оно приходит конкретному пользователю.
Как можно поменять пользователя на другого?

**Comment by se-aplana** [comment]
Рассылка выполняется:
Всем линейным руководителям сотрудника (рекурсивно по столбцам "employee.manager" и "employee.manager2")
Руководителям проектов по которым сотрудник выполнял списания
Руководителю центра сотрудинка
Дополнительно списку адресов из столбца "region.additional_emails" для строки соотвествующей региону сотрудника

Алгоритм рассылки заложен в коде.

**Comment by vdvas** [comment]
Заявление приходит на подтверждение пользователю, который не является членом тех групп, которые указаны в алгоритме рассылки.
При просмотре заявлений оно сначала приходит этому пользователю и написано "на согласованиеи РПГ".
Что именно нужно указывать в "region.additional_emails"?
![default](https://cloud.githubusercontent.com/assets/9025124/9174584/6950a28a-3f89-11e5-8ffd-727206b99274.png)

**Comment by se-aplana** [comment]
РПГ - руководитель проектной группы - это означает что данный пользователь назначен руководителем проекта в одном из проектов на которые списывал занятость сотрудник

в "region.additional_emails" нужно указывать список email-адресов через точку с запятой

**Comment by vdvas** [comment]
этот пользователь не значится РП ни в одном из проектов.

**Comment by se-aplana** [comment]
В целом алгоритм выглядит так:
1)	Получаем список проектов, на которые сотрудник списывал занятость последние 2 недели.
2)	Получаем список проектов, на которые запланирована занятость у сотрудника.
3)	Проходим по списку проектов и определяем те, в которых он не руководитель.
4)	Если полученный список проектов пуст, то ш. 8.
5)	По вновь полученному списку проектов получаем менеджеров (тим-лиды, старшие аналитики и др.) по запросу:
Query query = entityManager.createQuery("select pm.employee from ProjectManager as pm " +
                "where pm.project = :project and pm.active=:active and " +
                "pm.projectRole.id = :roleId and pm.employee not in " +
                "(select va.manager from VacationApproval as va where va.vacation = :vacation and va.result is not null)")
                .setParameter("project", project)
                .setParameter("active", true)
                .setParameter("roleId", vacation.getEmployee().getJob().getId())
                .setParameter("vacation", vacation);
6)	Всех этих менеджеров добавляем в рассылку, убрав повторяющихся.
7)	Рассылаем уведомления.
8)	После того как все менеджеры подтвердили отпуск, рассылаем уведомления линейному руководителю на согласование.
9)	После того как лин. руководитель согласовал – отпуск считается утвержденным.

**Comment by vdvas** [comment]
У меня такое ощущение что у нас РПГ это какой-то постоянное значение. Может быть где-то в бд есть записи о том кто является РПГ.
Потому что это один и тот же человек всегда и РПГ он реально не является ни в одном проекте.
Вопрос по алгоритму: 
Кто такие менеджеры, тим-лиды и старшие аналитики? Имеете ввиду в свойствах проекта роли сотрудников?
Как выполнить запрос который вы написали в пункте 5?

**Comment by vdvas** [comment]
Снова поднимаю вопрос по заявлениям на отпуск. Письмо об успешном согласовании отпуска приходит человеку, который не является руководителем.
