### ISSUE TITLE
Типы активностей

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#42]
В последнее время часто приходят отчеты об ошибках при отправлении отчетов пользователями.
Из последних изменений в системе было создание вручную новых типов активностей в dictionary_item, а также добавление этой активности разным сотрудникам в  available_activity_category.
Но затем узнал что без правки кода новые активности создавать нельзя.
Думаю что удаление этих типов может решить проблему.
Но боюсь что отчеты в которых использовался этот тип активности повредятся.
Посоветуйте как лучше избавиться от этих типов активностей.
Если требуется удаление отчетов, то как найти все отчеты с определенным типом активности?

**Comment by se-aplana** [comment]
выполните в БД запрос: select * from time_sheet_detail where act_type = N
где N - id необходимой активности

вообще БД не даст удалить записи если на них есть ссылки

удалять отчеты не обязательно, можете выполнить update заменив id активности на другие
