### ISSUE TITLE
Проектная роль

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#43]
Здравствуйте.
В таблице project role  имеются 6 ролей.
Однако при составлении отчета отображается только 5.
В редактировании проектов  при добавлении сотрудника в разделе проектные роли все 6 ролей отображаются.
При сохранении и повторном редактировании роль меняется на "не определена".

**Comment by se-aplana** [comment]
добрый день
в редактировании проектов так же должно отображаться 5 ролей, роль "не определена" является резервной и используется только для синхронизации с LDAP - это баг, запланировано его исправление

**Comment by vdvas** [comment]
отправил на timesheet@aplana.com скриншоты и дамп.

**Comment by se-aplana** [comment]
названия ролей фиксированы в классе ProjectRolesEnum
после их изменения система не может их распознать
так же роль "Не определена" не должна использоваться как активная (id=10), т.к. это резервная внутренняя роль
