### ISSUE TITLE
Пришло письмо об ошибке

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#44]
Что это может значить?

У пользователя Анастасия Мартынова произошла следующая ошибка:
java.util.NoSuchElementException

Параметры запроса: employeeId : [863]
timeSheetTablePart[0].activityTypeId : [0]
overtimeCauseComment : [отпуск]
calDate : [2016-10-04]
plan : []
divisionId : [6]
overtimeCause : [0]
effortInNextDay : [125]
typeOfCompensation : [0]
Stack trace: 
[com.aplana.timesheet.util.EnumsUtils.getEnumById(EnumsUtils.java:22), com.aplana.timesheet.service.TimeSheetService.storeTimeSheet(TimeSheetService.java:164), com.aplana.timesheet.service.TimeSheetService$$FastClassByCGLIB$$d7c6a842.invoke(), net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191), org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150), org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172), org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622), com.aplana.timesheet.service.TimeSheetService$$EnhancerByCGLIB$$74de1418.storeTimeSheet(), com.aplana.timesheet.controller.TimeSheetController.sendTimeSheet(TimeSheetController.java:188), com.aplana.timesheet.controller.TimeSheetController$$FastClassByCGLIB$$ff07c422.invoke(), net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191), org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150), org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172), org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622), com.aplana.timesheet.controller.TimeSheetController$$EnhancerByCGLIB$$63630682.sendTimeSheet(), sun.reflect.GeneratedMethodAccessor220.invoke(Unknown Source), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:622), org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:213), org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126), org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96), org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617), org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578), org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80), org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923), org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852), org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882), org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789), javax.servlet.http.HttpServlet.service(HttpServlet.java:637), javax.servlet.http.HttpServlet.service(HttpServlet.java:717), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206), com.cj.xss.XSSFilter.doFilter(Unknown Source), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206), com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129), com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206), org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311), org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116), org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83), org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323), org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113), org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323), org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:101), org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323), org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113), org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323), org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:146), org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323), org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54), org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323), org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45), org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323), org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150), org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323), org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:182), org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323), org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105), org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323), org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87), org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323), org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173), org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346), org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206), org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:147), org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206), org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88), org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206), org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233), org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191), org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127), org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102), org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109), org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293), org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859), org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602), org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489), java.lang.Thread.run(Thread.java:701)]

**Comment by se-aplana** [comment]
в коде жестко фиксирован список регионов
    OTHERS(1, "Остальные регионы"),
    UFA(2, "Уфа"),
    MOSCOW(3, "Москва"),
    PERM(4, "Пермь"),
    NIJNIY_NOVGOROD(5, "Нижний Новгород");

похоже что в БД добавили новый регион. нужно откатить изменения по регионам.

**Comment by vdvas** [comment]
Не добавлял в БД новый регион. Я редактировал существующие, но это было давно и ошибок раньше не было.

	id	 name	              ldap_city	additional_emails
        5   Санкт-Петербург	SPB
        id      name	              ldap_city	additional_emails
         1   Остальные регионы	    OTH

**Comment by se-aplana** [comment]
судя по:
overtimeCause : [0]
typeOfCompensation : [0]

пользователь не указал причину недоработки и типа компенсации
если система не предлагает их указать, попробуйте очистить кеш/куки и повторить операцию
