### ISSUE TITLE
не работает сервер

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#46]
Сервер timesheet и контроллер домена планово перезагружались накануне.
При попытке войти в систему пишет ошибку

HTTP Status 500 -

type Exception report

message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

org.springframework.ldap.CommunicationException: srv-dc.rumpu.ru:389; nested exception is javax.naming.CommunicationException: srv-dc.rumpu.ru:389 [Root exception is java.net.UnknownHostException: srv-dc.rumpu.ru]
	org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:100)
	org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.bindAsUser(ActiveDirectoryLdapAuthenticationProvider.java:170)
	org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.doAuthentication(ActiveDirectoryLdapAuthenticationProvider.java:111)
	org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:61)
	org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:156)
	org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174)
	org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94)
	org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:194)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	com.aplana.timesheet.system.security.AutentificationFilter.doFilter(AutentificationFilter.java:30)
	org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:147)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
root cause

javax.naming.CommunicationException: srv-dc.rumpu.ru:389 [Root exception is java.net.UnknownHostException: srv-dc.rumpu.ru]
	com.sun.jndi.ldap.Connection.<init>(Connection.java:223)
	com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:136)
	com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1598)
	com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2643)
	com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:306)
	com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:193)
	com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:211)
	com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
	com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
	javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	javax.naming.InitialContext.init(InitialContext.java:240)
	javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:151)
	org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider$ContextFactory.createContext(ActiveDirectoryLdapAuthenticationProvider.java:311)
	org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.bindAsUser(ActiveDirectoryLdapAuthenticationProvider.java:164)
	org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.doAuthentication(ActiveDirectoryLdapAuthenticationProvider.java:111)
	org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:61)
	org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:156)
	org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174)
	org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94)
	org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:194)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	com.aplana.timesheet.system.security.AutentificationFilter.doFilter(AutentificationFilter.java:30)
	org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:147)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
root cause

java.net.UnknownHostException: srv-dc.rumpu.ru
	java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:175)
	java.net.SocksSocketImpl.connect(SocksSocketImpl.java:385)
	java.net.Socket.connect(Socket.java:546)
	java.net.Socket.connect(Socket.java:495)
	java.net.Socket.<init>(Socket.java:392)
	java.net.Socket.<init>(Socket.java:206)
	com.sun.jndi.ldap.Connection.createSocket(Connection.java:365)
	com.sun.jndi.ldap.Connection.<init>(Connection.java:200)
	com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:136)
	com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1598)
	com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2643)
	com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:306)
	com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:193)
	com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:211)
	com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
	com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
	javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	javax.naming.InitialContext.init(InitialContext.java:240)
	javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:151)
	org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider$ContextFactory.createContext(ActiveDirectoryLdapAuthenticationProvider.java:311)
	org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.bindAsUser(ActiveDirectoryLdapAuthenticationProvider.java:164)
	org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.doAuthentication(ActiveDirectoryLdapAuthenticationProvider.java:111)
	org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:61)
	org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:156)
	org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174)
	org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94)
	org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:194)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	com.aplana.timesheet.system.security.AutentificationFilter.doFilter(AutentificationFilter.java:30)
	org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:147)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
note The full stack trace of the root cause is available in the Apache Tomcat/6.0.35 logs.

Apache Tomcat/6.0.35

**Comment by se-aplana** [comment]
ошибка при подключении к LDAP CommunicationException: srv-dc.rumpu.ru:389
похоже у вас не резволвится хост UnknownHostException: srv-dc.rumpu.ru
проверьте DNS или зимените настройки приложения на корректный адрес LDAP
