### ISSUE TITLE
Почтовые уведомления о подборе пароля.

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#47]
Здравствуйте.
Пользователю, который наделен правами администрирования системы приходят такие сообщения:
"Зафиксированы попытки подбора пароля для доступа к системе, подробности в логах сервера."
Как их отключить?

**Comment by se-aplana** [comment]
В настройках есть параметр mail.ProblemsAndProposals.toaddress, из которого берется адрес для письма. 
Однако на этот же параметр завязаны сообщения об ошибка, обратная связь через форму и проблемы при входе в систему.
Возможности отключить только уведомления о подборе пароля невозможно.

**Comment by vdvas** [comment]
Нашел. Спасибо.
Чтобы изменения применились что нужно сделать?

**Comment by se-aplana** [comment]
остановить и запустить tomcat
