### ISSUE TITLE
Отключение почтовых уведомлений

### ISSUE THREAD

**Issue by vdvas** [itru/timesheet#48]
Здравствуйте.
Необходимо отключить все почтовые уведомления.
В файле /etc/tomcat6/timesheet.properties
я указал
mail.send.enable=false
Далее перезапустил tomcat командой
/etc/init.d/tomcat6 restart
Этого достаточно?

**Comment by se-aplana** [comment]
да, этого должно быть достаточно.
как альтернативный вариант указать mail.smtp.host=localhost
чтобы timesheet физически не мог подключиться к почтовому серверу
